/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_integrador_crud.gui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author jonatan
 */
public class MainFrame extends JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        setTitle("Sistema de ventas");
        setBounds(400, 200, 400, 500);
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.jpg")).getImage());
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MainTitlePanel = new javax.swing.JPanel();
        MainTitleLabel = new javax.swing.JLabel();
        EnterOptionsPanel = new javax.swing.JPanel();
        ManagerSelectionButton = new javax.swing.JButton();
        EmployeeSelectionButton = new javax.swing.JButton();
        SellerSelectionButton = new javax.swing.JButton();
        ClientSelectionButton = new javax.swing.JButton();
        MainExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(0, 102, 0));

        MainTitlePanel.setBackground(new java.awt.Color(0, 153, 153));

        MainTitleLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        MainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainTitleLabel.setText("SISTEMA DE VENTAS");

        javax.swing.GroupLayout MainTitlePanelLayout = new javax.swing.GroupLayout(MainTitlePanel);
        MainTitlePanel.setLayout(MainTitlePanelLayout);
        MainTitlePanelLayout.setHorizontalGroup(
            MainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        MainTitlePanelLayout.setVerticalGroup(
            MainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainTitlePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(MainTitleLabel)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        EnterOptionsPanel.setBackground(new java.awt.Color(204, 204, 0));

        ManagerSelectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ManagerIcon.jpg"))); // NOI18N
        ManagerSelectionButton.setText("Administrador");
        ManagerSelectionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManagerSelectionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ManagerSelectionButton.setPreferredSize(new java.awt.Dimension(150, 50));
        ManagerSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerSelectionButtonActionPerformed(evt);
            }
        });

        EmployeeSelectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EmployeeIcon.jpg"))); // NOI18N
        EmployeeSelectionButton.setText("Empleado");
        EmployeeSelectionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmployeeSelectionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EmployeeSelectionButton.setPreferredSize(new java.awt.Dimension(150, 50));

        SellerSelectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SellerIcon.gif"))); // NOI18N
        SellerSelectionButton.setText("Vendedor");
        SellerSelectionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SellerSelectionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SellerSelectionButton.setPreferredSize(new java.awt.Dimension(150, 50));

        ClientSelectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ClientIcon.jpg"))); // NOI18N
        ClientSelectionButton.setText("Cliente");
        ClientSelectionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ClientSelectionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ClientSelectionButton.setPreferredSize(new java.awt.Dimension(150, 50));

        MainExitButton.setText("Salir");
        MainExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnterOptionsPanelLayout = new javax.swing.GroupLayout(EnterOptionsPanel);
        EnterOptionsPanel.setLayout(EnterOptionsPanelLayout);
        EnterOptionsPanelLayout.setHorizontalGroup(
            EnterOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterOptionsPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(EnterOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManagerSelectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SellerSelectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(EnterOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeSelectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClientSelectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterOptionsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EnterOptionsPanelLayout.setVerticalGroup(
            EnterOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnterOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeSelectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(ManagerSelectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(EnterOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClientSelectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(SellerSelectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EnterOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnterOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MainExitButtonActionPerformed

    private void ManagerSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerSelectionButtonActionPerformed
        ManagerFrame managerFrame=new ManagerFrame();
        managerFrame.setVisible(true);
        managerFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_ManagerSelectionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClientSelectionButton;
    private javax.swing.JButton EmployeeSelectionButton;
    private javax.swing.JPanel EnterOptionsPanel;
    private javax.swing.JButton MainExitButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MainTitleLabel;
    private javax.swing.JPanel MainTitlePanel;
    private javax.swing.JButton ManagerSelectionButton;
    private javax.swing.JButton SellerSelectionButton;
    // End of variables declaration//GEN-END:variables
}
