/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_integrador_crud.gui;

/**
 *
 * @author jonatan
 */
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import proyecto_integrador_crud.data.*;
import proyecto_integrador_crud.object.*;
public class ManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagerFrame
     */
    public ManagerFrame() {
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.jpg")).getImage());
        initComponents();
        paintTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ManagerNameTxt = new javax.swing.JLabel();
        ManagerLastnameTxt = new javax.swing.JLabel();
        ManagerDniTxt = new javax.swing.JLabel();
        ManagerEmailTxt = new javax.swing.JLabel();
        ManagerAddressTxt = new javax.swing.JLabel();
        ManagerPhoneTxt = new javax.swing.JLabel();
        ManagerSexTxt = new javax.swing.JLabel();
        ManagerNameField = new javax.swing.JTextField();
        ManagerLastNameField = new javax.swing.JTextField();
        ManagerDniField = new javax.swing.JTextField();
        ManagerEmailField = new javax.swing.JTextField();
        ManagerAddressField = new javax.swing.JTextField();
        ManagerPhoneField = new javax.swing.JTextField();
        ManagerGenderComboB = new javax.swing.JComboBox();
        ManagerAddButton = new javax.swing.JButton();
        ManagerUpdateButton = new javax.swing.JButton();
        ManagerDeleteButton = new javax.swing.JButton();
        ManagerExitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManagerUsersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        ManagerNameTxt.setText("Name");

        ManagerLastnameTxt.setText("Last Name");

        ManagerDniTxt.setText("DNI");

        ManagerEmailTxt.setText("Email");

        ManagerAddressTxt.setText("Address");

        ManagerPhoneTxt.setText("Phone");

        ManagerSexTxt.setText("Gender");

        ManagerNameField.setPreferredSize(new java.awt.Dimension(150, 30));

        ManagerLastNameField.setPreferredSize(new java.awt.Dimension(150, 30));

        ManagerDniField.setPreferredSize(new java.awt.Dimension(150, 30));

        ManagerEmailField.setPreferredSize(new java.awt.Dimension(150, 30));

        ManagerAddressField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ManagerAddressField.setMinimumSize(new java.awt.Dimension(150, 30));
        ManagerAddressField.setPreferredSize(new java.awt.Dimension(150, 30));

        ManagerPhoneField.setPreferredSize(new java.awt.Dimension(150, 30));
        ManagerPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerPhoneFieldActionPerformed(evt);
            }
        });

        ManagerGenderComboB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other" }));
        ManagerGenderComboB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerGenderComboBActionPerformed(evt);
            }
        });

        ManagerAddButton.setText("Add");
        ManagerAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerAddButtonActionPerformed(evt);
            }
        });

        ManagerUpdateButton.setText("Update");

        ManagerDeleteButton.setText("Delete");
        ManagerDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerDeleteButtonActionPerformed(evt);
            }
        });

        ManagerExitButton.setText("Exit");
        ManagerExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerExitButtonActionPerformed(evt);
            }
        });

        ManagerUsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Last Name", "DNI", "Email", "Address", "Phone", "Gender"
            }
        ));
        ManagerUsersTable.setName(""); // NOI18N
        ManagerUsersTable.setNextFocusableComponent(ManagerDniField);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ManagerNameField, org.jdesktop.beansbinding.ObjectProperty.create(), ManagerUsersTable, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding.bind();
        jScrollPane1.setViewportView(ManagerUsersTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManagerEmailTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ManagerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManagerNameTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ManagerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManagerLastnameTxt)
                                .addGap(18, 18, 18)
                                .addComponent(ManagerLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManagerDniTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ManagerDniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ManagerAddressTxt)
                            .addComponent(ManagerPhoneTxt)
                            .addComponent(ManagerSexTxt))
                        .addGap(0, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ManagerPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ManagerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ManagerGenderComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ManagerAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(ManagerUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManagerDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManagerExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManagerNameTxt)
                    .addComponent(ManagerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManagerAddressTxt)
                    .addComponent(ManagerAddButton)
                    .addComponent(ManagerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ManagerUpdateButton)
                            .addComponent(ManagerPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManagerPhoneTxt))
                        .addGap(19, 19, 19)
                        .addComponent(ManagerDeleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ManagerLastnameTxt)
                            .addComponent(ManagerLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ManagerDniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManagerSexTxt)
                            .addComponent(ManagerDniTxt)
                            .addComponent(ManagerGenderComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ManagerEmailTxt)
                        .addComponent(ManagerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ManagerExitButton))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManagerPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManagerPhoneFieldActionPerformed

    private void ManagerGenderComboBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerGenderComboBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManagerGenderComboBActionPerformed

    private void ManagerDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerDeleteButtonActionPerformed
        //DeletePerson();
        if (ManagerUsersTable.getSelectedRow() != -1) {
            int[] row = ManagerUsersTable.getSelectedRows();
            //String ids = jTable.getValueAt(row[0], 0).toString();
            String ids = ManagerUsersTable.getValueAt(row[0], 0).toString();
            System.out.println("selected: " + ids);
            int id = Integer.parseInt(ids);
            mData.delete(id);
            paintTable();
        }
    }//GEN-LAST:event_ManagerDeleteButtonActionPerformed

    private void ManagerAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerAddButtonActionPerformed
        //AddPerson();
        Manager m=new Manager();
        m.setName(this.ManagerNameField.getText());
        m.setLastname(this.ManagerLastNameField.getText());
        m.setDni(this.ManagerDniField.getText());
        m.setEmail(this.ManagerEmailField.getText());
        m.setAddress(this.ManagerAddressField.getText());
        m.setPhone(this.ManagerPhoneField.getText());
        m.setSex(this.ManagerGenderComboB.getSelectedItem().toString());
        mData.create(m);
        paintTable();
        this.ManagerNameField.setText("");
        this.ManagerLastNameField.setText("");
        this.ManagerDniField.setText("");
        this.ManagerEmailField.setText("");
        this.ManagerAddressField.setText("");
        this.ManagerPhoneField.setText("");
    }//GEN-LAST:event_ManagerAddButtonActionPerformed

    private void ManagerExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ManagerExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }
    Manager m=new Manager();
    ManagerData mData=new ManagerData();
    private void paintTable() {
        DefaultTableModel modelo = (DefaultTableModel) ManagerUsersTable.getModel();
        List<Manager> lis = mData.list();
        while (modelo.getRowCount() > 0)
            modelo.removeRow(0);
        for (Manager m : lis) {
            modelo.addRow(new Object[] { m.getId(), m.getName(),m.getLastname(),m.getDni(),m.getEmail(),
                m.getAddress(),m.getPhone(), m.getSex() });
        }
    }
    
     void initForm() {
       

        ManagerUsersTable = new JTable();
        ManagerUsersTable.setModel(new DefaultTableModel(new Object[][] {
                 
        }, new String[] { "ID", "Name", "Last Name","DNI","Email","Address","Phone","Sex" }));

        jScrollPane1 = new JScrollPane();
        jScrollPane1.setViewportView(ManagerUsersTable);

        
        
        
        
        add(jScrollPane1);
        

        // Manejo de eventos                                                         
        
    }
     private void AddPerson(ActionEvent e) {
        
            Manager m=new Manager();
            m.setName(this.ManagerNameField.getText());
            m.setSex(this.ManagerGenderComboB.getSelectedItem().toString());
            mData.create(m);
            paintTable();
            this.ManagerNameField.setText("");
            
        
    }
     private void DeletePerson(ActionEvent e) {
        if (ManagerUsersTable.getSelectedRow() != -1) {
            int[] row = ManagerUsersTable.getSelectedRows();
            //String ids = jTable.getValueAt(row[0], 0).toString();
            String ids = ManagerUsersTable.getValueAt(row[0], 0).toString();
            int id = Integer.parseInt(ids);
            mData.delete(id);
            paintTable();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManagerAddButton;
    private javax.swing.JTextField ManagerAddressField;
    private javax.swing.JLabel ManagerAddressTxt;
    private javax.swing.JButton ManagerDeleteButton;
    private javax.swing.JTextField ManagerDniField;
    private javax.swing.JLabel ManagerDniTxt;
    private javax.swing.JTextField ManagerEmailField;
    private javax.swing.JLabel ManagerEmailTxt;
    private javax.swing.JButton ManagerExitButton;
    private javax.swing.JComboBox ManagerGenderComboB;
    private javax.swing.JTextField ManagerLastNameField;
    private javax.swing.JLabel ManagerLastnameTxt;
    private javax.swing.JTextField ManagerNameField;
    private javax.swing.JLabel ManagerNameTxt;
    private javax.swing.JTextField ManagerPhoneField;
    private javax.swing.JLabel ManagerPhoneTxt;
    private javax.swing.JLabel ManagerSexTxt;
    private javax.swing.JButton ManagerUpdateButton;
    private javax.swing.JTable ManagerUsersTable;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    //private JTable ManagerUsersTable;
    //private JScrollPane jScrollPane1;
}
